### ISSUE TITLE
Please consider merging your work

### ISSUE THREAD

**Issue by pcav** [tsw-apropos/qtilestools#1]
Having multiple plugins doing apparently similar tasks is confusing for users. Would it be feasible to merge your work into the existing QTiles plugin?
Thanks.

**Comment by aproposinfosystems** [comment]
I am very open to having it merged. This plug-in is a stop gap measure to address a need.

**Comment by pcav** [comment]
Thanks. So I hope you do not mind if I wait the outcome of this discussion before eventually publish your work as a standalone plugin.
